routes/web.php
<?php
Auth::routes();

Route::post('auth/admin-login', 'Auth\LoginController@adminLogin')->name('auth.admin.login');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/', 'Redirect@render')->name('index');
});

Route::group(['middleware' => ['user', \App\Http\Middleware\CheckBanned::class]], function () {

    Route::get('notifications/ajax/get', 'NotificationController@ajax')->name('notifications.ajax');
    Route::post('notifications/ajax/read/{id}', 'NotificationController@read')->name('notifications.read');

    Route::post('rcon/follow-user','GeneralController@followUser')->name('rcon.follow.user');
    Route::post('rcon/join-room','GeneralController@joinRoom')->name('rcon.join.room');
    Route::post('change-theme','GeneralController@changeTheme')->name('change.theme');

    Route::group(['namespace' => 'Home'], function () {
        Route::get('me', 'Me@render')->name('me');

        Route::group(['middleware' => [\App\Http\Middleware\CheckStaffPin::class]],function () {
            Route::get('client', 'Client@render')->name('client');
        });

        Route::get('logout', 'Logout@render')->name('logout');
    });

    Route::group(['namespace' => 'Article'], function () {
        Route::get('news', 'NewsController@render')->name('NewsController');
        Route::get('news/{articles}', 'NewsController@show')->name('article.show');
        Route::post('news/{article}/reaction', 'ReactionController@store')->name('article.reaction.create');
        Route::post('reaction/{reaction}/delete', 'ReactionController@destroy')->name('article.reaction.delete');
    });

    Route::group(['namespace' => 'Settings'], function () {
        Route::get('settings/password', 'PasswordController@index')->name('settings.password.index');
        Route::post('settings/password', 'PasswordController@store')->name('settings.password.store');
    });

    Route::group(['namespace' => 'Staff'], function () {
        Route::get('staff', 'StaffController@index')->name('Staff');
    });

    Route::group(['namespace' => 'Community', 'prefix' => 'community'], function () {
        Route::get('top_players', 'TopPlayersController@index')->name('top_players');
    });

    Route::group(['namespace' => 'Pin', 'prefix' => 'housekeeping', 'as' => 'housekeeping.'], function () {
        Route::get('user/pin/', 'PinController@pin')->name('user.pin');
        Route::post('user/pin/', 'PinController@check')->name('user.pin.check');
        Route::get('user/pin/create', 'PinController@create')->name('user.pin.create');
        Route::post('user/pin/create', 'PinController@store')->name('user.pin.store');
    });

    Route::group(['middleware' => [\App\Http\Middleware\CheckStaff::class,\App\Http\Middleware\CheckStaffPin::class], 'namespace' => 'Housekeeping', 'prefix' => 'housekeeping', 'as' => 'housekeeping.'], function () {
        Route::get('index', 'IndexController@index')->name('index');

        //News
        Route::resource('news', 'NewsController');
        Route::get('get/news/', 'NewsController@indexAjax')->name('news.indexAjax');

        //worldfilter
        Route::resource('wordfilter', 'WordfilterController');
        Route::get('get/wordfilter/', 'WordfilterController@indexAjax')->name('wordfilter.indexAjax');

        //Cms settings
        Route::resource('cms_settings', 'CmsSettingsController');
        Route::get('get/cms_settings/', 'CmsSettingsController@indexAjax')->name('cms_settings.indexAjax');

        //Players
        Route::resource('player', 'PlayerController');
        Route::get('get/player/', 'PlayerController@indexAjax')->name('player.indexAjax');
        Route::post('player/disconnect', 'PlayerController@disconnectUserAjax')->name('player.disconnectUserAjax');

    });


});

app/Http/Controllers/Article/NewsController.php
<?php
namespace App\Http\Controllers\Article;

use App\Http\Controllers\Controller;
use App\Models\Website\Article;

class NewsController extends Controller
{

    public function render ()
    {
        return view('pages.user.articles.news');
    }

    public function show(Article $articles) {
        $view = view('pages.user.articles.news');
        $view->article = $articles;
        $view->newsArticles = Article::orderBy('id','DESC')->get();

        return $view;
    }

}

app/Http/Controllers/Housekeeping/CmsSettingsController.php
<?php

namespace App\Http\Controllers\Housekeeping;

use App\Http\Controllers\Controller;
use App\Models\Website\CmsSettings;
use App\Notifications\GlobalNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class CmsSettingsController extends Controller
{
    public function index()
    {
        $view = view('pages.housekeeping.cms_settings.index');
        $view->settings = CmsSettings::all();

        return $view;
    }


    public function edit($key)
    {
        $view = view('pages.housekeeping.cms_settings.edit');
        $view->cms_setting = CmsSettings::where('key', $key)->first();

        return $view;
    }


    public function update(Request $request, $key)
    {
        $cms_setting = CmsSettings::where('key', $key)->first();
        $cms_setting->update($request->all());

        Auth::user()->notify(new GlobalNotification(__('Cms setting successfully updated'), 'success'));


        return redirect()->route('housekeeping.cms_settings.edit', $key);
    }

    public function indexAjax(Datatables $datatables)
    {
        $builder = CmsSettings::query()->select('key', 'value');

        return $datatables->eloquent($builder)
            ->addColumn('action', function ($cms_settings) {
                return '<a href="' . route('housekeeping.cms_settings.edit', [$cms_settings->key]) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i>' . __('Edit') .'</a>';
            })->rawColumns(['action'])->make(true);
    }

}

app/Http/Controllers/Housekeeping/IndexController.php
<?php
namespace App\Http\Controllers\Housekeeping;

use App\Http\Controllers\Controller;
use App\Models\Player\User;

class IndexController extends Controller
{

    public function index()
    {
        $view = view('pages.housekeeping.index');
        $view->last_version = $this->getVersion();
        $view->last_players = User::orderBy('account_created', 'DESC')->get()->take(5);

        return $view;
    }

    function getVersion() {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://vindretros.nl/braincms.txt');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch,CURLOPT_USERAGENT,'LaraCMS version checker: '. config('hotel.lara_cms_version'));
        $output = curl_exec($ch);
        curl_close($ch);

        return $output;
    }

}

app/Http/Controllers/Housekeeping/NewsController.php
<?php

namespace App\Http\Controllers\Housekeeping;

use App\Http\Controllers\Controller;
use App\Http\Requests\newsStoreRequest;
use App\Models\Website\Article;
use App\Notifications\GlobalNotification;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class NewsController extends Controller
{

    public function index()
    {
        $view = view('pages.housekeeping.news.index');
        $view->news = Article::all();

        return $view;
    }

    public function create()
    {
        $view = view('pages.housekeeping.news.create');
        $images = File::files(public_path() . '/images/news');
        $imageList = [];
        foreach ($images as $image) {
            $imageList[$image->getFilename()] = $image->getFilename();
        }
        $view->images = $imageList;


        return $view;
    }


    public function store(newsStoreRequest $request)
    {
        $article = Article::create($request->all());
        $article->user()->associate(Auth::user()->id)->save();
        Auth::user()->notify(new GlobalNotification(__('News article saved'), 'success'));

        return redirect()->route('housekeeping.news.edit', $article);
    }

    public function edit(Article $news)
    {
        $view = view('pages.housekeeping.news.edit');
        $images = File::files(public_path() . '/images/news');
        $imageList = [];
        foreach ($images as $image) {
            $imageList[$image->getFilename()] = $image->getFilename();
        }
        $view->images = $imageList;
        $view->news = $news;


        return $view;

    }

    public function update(newsStoreRequest $request, Article $news)
    {
        $article = $news->update($request->all());
        Auth::user()->notify(new GlobalNotification(__('News article updated'), 'success'));

        return redirect()->route('housekeeping.news.edit', $article);
    }

    public function destroy(Article $news)
    {
        $news->delete();

        return redirect()->route('housekeeping.news.index');
    }


    public function indexAjax(Datatables $datatables)
    {
        $builder = Article::query()->select('id', 'title', 'description', 'content', 'created_at');

        return $datatables->eloquent($builder)
            ->addColumn('action', function ($news) {
                return '<a href="' . route('housekeeping.news.edit', [$news->id]) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i>' . __('Edit') .'</a>';
            })->rawColumns(['action'])->make(true);
    }
}

app/Http/Controllers/Housekeeping/PlayerController.php
<?php

namespace App\Http\Controllers\Housekeeping;

use App\Helpers\Rcon;
use App\Helpers\Site;
use App\Http\Controllers\Controller;
use App\Http\Requests\userStoreRequest;
use App\Models\Player\User;
use App\Notifications\GlobalNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class PlayerController extends Controller
{

    public function index()
    {
        return view('pages.housekeeping.player.index');
    }


    public function edit(User $player)
    {
        $view = view('pages.housekeeping.player.edit');
        $view->player = $player;

        return $view;

    }

    public function update(userStoreRequest $request, User $player)
    {
        if ((int)$player->id === Auth::user()->id || Auth::user()->rank <= $player->rank || Auth::user()->rank <= $request->get('rank')) {
            Auth::user()->notify(new GlobalNotification(__('You are not allowed to modify this user!'), 'danger'));
            return redirect()->route('housekeeping.player.index');
        }
        $player->update($request->all());
        $player->diamonds()->update(['amount' => $request->get('diamonds')]);
        $player->duckets()->update(['amount' => $request->get('duckets')]);

        $player->rank()->associate($request->get('rank'))->save();
        Auth::user()->notify(new GlobalNotification(__('User successfull saved!'), 'success'));

        return redirect()->route('housekeeping.player.edit', [$player]);
    }

    public function indexAjax(Datatables $datatables)
    {
        $builder = User::query()->select('id', 'username', 'rank', 'credits');

        return $datatables->eloquent($builder)
            ->addColumn('duckets', function ($player) {
                return $player->duckets->amount;
            })
            ->addColumn('diamonds', function ($player) {
                return $player->diamonds->amount ?? 0;
            })
            ->addColumn('action', function ($player) {
                return '<a href="' . route('housekeeping.player.edit', [$player->id]) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i>' . __('Edit') .'</a>';
            })->rawColumns(['action'])->make(true);
    }

    public function disconnectUserAjax(Request $request) {
        Rcon::disconectUser($request->get('user_id'));

        return 'Ok';
    }

}

app/Http/Controllers/Housekeeping/WordfilterController.php
<?php

namespace App\Http\Controllers\Housekeeping;

use App\Helpers\Rcon;
use App\Http\Controllers\Controller;
use App\Http\Requests\createWordFilterRequest;
use App\Http\Requests\updateWordFilterRequest;
use App\Models\Website\Wordfilter;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class WordfilterController extends Controller
{

    public function index()
    {
        return view('pages.housekeeping.wordfilter.index');
    }


    public function create()
    {
        return view('pages.housekeeping.wordfilter.create');
    }


    public function store(createWordFilterRequest $request)
    {
        $wordfilter = WordFilter::create([
            'key' => $request->get('key'),
            'replacement' => $request->get('replacement'),
            'hide' => $request->get('hide'),
            'report' => $request->get('report'),
            'mute' => $request->get('mute'),
        ]);
        Rcon::reloadWordFilter();

        return redirect()->route('housekeeping.wordfilter.edit', [$request->get('key')]);
    }


    public function edit(Wordfilter $wordfilter)
    {
        $view = view('pages.housekeeping.wordfilter.edit');
        $view->filter = $wordfilter;

        return $view;
    }


    public function update(updateWordFilterRequest $request, Wordfilter $wordfilter)
    {
        $wordfilter->update([
            'key' => $request->get('key'),
            'replacement' => $request->get('replacement'),
            'hide' => $request->get('hide'),
            'report' => $request->get('report'),
            'mute' => $request->get('mute'),
        ]);
        Rcon::reloadWordFilter();

        return redirect()->route('housekeeping.wordfilter.edit', [$wordfilter]);
    }

    public function destroy($id)
    {
        //
    }

    public function indexAjax(Datatables $datatables)
    {
        $builder = Wordfilter::query()->select('key', 'replacement', 'hide', 'report', 'mute');

        return $datatables->eloquent($builder)
            ->addColumn('action', function ($filter) {
                return '<a href="' . route('housekeeping.wordfilter.edit', [$filter->key]) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i>' . __('Edit') .'</a>';
            })->rawColumns(['action'])->make(true);
    }
}

resources/views/pages/housekeeping/news/create.blade.php
@extends('layouts.housekeeping')

@section('title', __('News create'))

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-0 font-weight-bold text-primary">{{ __('News create') }}</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            {{ Form::open(['route' => ['housekeeping.news.store', 'method' => 'post']]) }}

            <div class="form-group">
                {{ Form::label('title', __('Title')) }}
                {{ Form::text('title',null, ['class' => 'form-control']) }}
                {!! $errors->first('title', '<p class="help-block text-danger">:message</p>') !!}
            </div>

            <div class="form-group">
                {{ Form::label('image',__('Image')) }}
                {{ Form::select('image', $images,null, ['class' => 'form-control', 'id' => 'image']) }}
                {!! $errors->first('image', '<p class="help-block text-danger">:message</p>') !!}
                <a href="#" id="preview" target="_blank">{{ __('Preview') }}</a>
            </div>
            <div class="form-group">
                {{ Form::label('description', __('Description')) }}
                {{ Form::text('description',null, ['class' => 'form-control']) }}
                {!! $errors->first('description', '<p class="help-block text-danger">:message</p>') !!}
            </div>

            <div class="form-group">
                {{ Form::label('content', __('Content')) }}
                {{ Form::textArea('content',null, ['class' => 'ckeditor']) }}
                {!! $errors->first('content', '<p class="help-block text-danger">:message</p>') !!}
            </div>


            {{Form::submit(__('Create'), ['class' => 'btn btn-success float-right'])}}

            {{ Form::close() }}
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $("#image").change(function () {
            $("#preview").attr("href", BASE_URL + '/images/news/' + $("#image").val());
        });
    </script>
@endsection

resources/views/pages/housekeeping/news/edit.blade.php
@extends('layouts.housekeeping')

@section('title', __('News edit'))

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-0 font-weight-bold text-primary">{{ __('News edit') }}</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            {{ Form::model($news,['route' => ['housekeeping.news.update',$news->id],'method' => 'put']) }}

            <div class="form-group">
                {{ Form::label('title', __('Title')) }}
                {{ Form::text('title',null, ['class' => 'form-control']) }}
                {!! $errors->first('title', '<p class="help-block text-danger">:message</p>') !!}
            </div>

            <div class="form-group">
                {{ Form::label('image',__('Image')) }}
                {{ Form::select('image', $images,null, ['class' => 'form-control', 'id' => 'image']) }}
                {!! $errors->first('image', '<p class="help-block text-danger">:message</p>') !!}
                <a href="#" id="preview" target="_blank">{{ __('Preview') }}</a>
            </div>
            <div class="form-group">
                {{ Form::label('description', __('Description')) }}
                {{ Form::text('description',null, ['class' => 'form-control']) }}
                {!! $errors->first('description', '<p class="help-block text-danger">:message</p>') !!}
            </div>

            <div class="form-group">
                {{ Form::label('content', __('Content')) }}
                {{ Form::textArea('content',null, ['class' => 'ckeditor']) }}
                {!! $errors->first('content', '<p class="help-block text-danger">:message</p>') !!}
            </div>


            {{Form::submit(__('Update'), ['class' => 'btn btn-success float-right'])}}

            {{ Form::close() }}
            {{Form::open(['method' => 'DELETE', 'route' => ['housekeeping.news.destroy', $news], 'onsubmit' => 'return confirmDelete()']) }}
            {{Form::submit(__('Delete') , ['class' => 'btn btn-danger'])}}
            {{ Form::close() }}
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $("#image").change(function () {
            $("#preview").attr("href", BASE_URL + '/images/news/' + $("#image").val());
        });

        function confirmDelete() {
            return confirm( {{ __('Are you sure you want to delete?') }});
        }
    </script>
@endsection

resources/views/pages/housekeeping/news/index.blade.php
@extends('layouts.housekeeping')

@section('title', __('News overview'))

@section('content')
    <h1 class="h3 mb-4 text-gray-800">{{ __('News overview') }}</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-2">
                    <h4 class="m-0 font-weight-bold text-primary">{{ __('News') }}</h4>
                </div>
                <div class="col-md-10">
                    <a href="{{route('housekeeping.news.create')}}" class="btn btn-success float-right">{{ __('Create') }}</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="table" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ __('Title') }}</th>
                        <th>{{ __('Description') }}</th>
                        <th>{{ __('Content') }}</th>
                        <th>{{ __('Created at') }}</th>
                        <th>{{ __('Edit') }}</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function () {
            $('#table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{route('housekeeping.news.indexAjax')}}',
                columns: [
                    {data: 'id'},
                    {data: 'title'},
                    {data: 'description'},
                    {data: 'content'},
                    {data: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });
    </script>
@endsection